name: credit_rating_transition
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - pip
  - pandas>=2.3.1
  - numpy>=2.2.6
  - matplotlib>=3.10.3
  - seaborn>=0.13.2
  - scikit-learn>=1.6.1
  - scipy>=1.15.3
  - plotly>=6.2.0
  - streamlit>=1.47.1
  - jupyter>=1.1.1
  - ipykernel>=6.30.0
  - requests>=2.32.4
  - beautifulsoup4>=4.13.4
  - lxml>=5.4.0
  - openpyxl>=3.1.5
  - xlrd>=2.0.0
  - python-dateutil>=2.9.0
  - selenium>=4.21.0
  - webdriver-manager>=4.0.2
  - httpx>=0.28.1
  - sqlalchemy>=1.4.0
  - pymongo>=4.0.0
  - python-dotenv>=1.1.1
  - tenacity>=9.1.2
  - tqdm>=4.67.1
  - lifelines>=0.30.0
  - openai>=1.97.1
  - pyyaml>=6.0.2
  - jinja2>=3.1.6
  - pip:
    - dart-fss>=0.4.13
    - scikit-survival>=0.24.1
    - altair>=5.5.0
    - ipython>=8.37.0
    - ipywidgets>=8.1.7
    - jupyterlab>=4.4.5
    - notebook>=7.4.4
    - pymsm>=0.0.3
    - pydeck>=0.9.1
    - watchdog>=6.0.0
    - gitpython>=3.1.45
    - fake-useragent>=2.2.0
    - xmltodict>=0.14.2
    - yaspin>=3.1.0 